/* 
 * REGISTRY API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AoosListResponse
    /// </summary>
    [DataContract]
    public partial class AoosListResponse :  IEquatable<AoosListResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AoosListResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AoosListResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AoosListResponse" /> class.
        /// </summary>
        /// <param name="aoos">aoos (required).</param>
        public AoosListResponse(List<AooInfo> aoos = default(List<AooInfo>))
        {
            // to ensure "aoos" is required (not null)
            if (aoos == null)
            {
                throw new InvalidDataException("aoos is a required property for AoosListResponse and cannot be null");
            }
            else
            {
                this.Aoos = aoos;
            }
        }
        
        /// <summary>
        /// Gets or Sets Aoos
        /// </summary>
        [DataMember(Name="aoos", EmitDefaultValue=false)]
        public List<AooInfo> Aoos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AoosListResponse {\n");
            sb.Append("  Aoos: ").Append(Aoos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AoosListResponse);
        }

        /// <summary>
        /// Returns true if AoosListResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AoosListResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AoosListResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Aoos == input.Aoos ||
                    this.Aoos != null &&
                    this.Aoos.SequenceEqual(input.Aoos)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Aoos != null)
                    hashCode = hashCode * 59 + this.Aoos.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
