/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CancellationToken
    /// </summary>
    [DataContract]
    public partial class CancellationToken :  IEquatable<CancellationToken>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CancellationToken" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public CancellationToken()
        {
        }
        
        /// <summary>
        /// Gets or Sets IsCancellationRequested
        /// </summary>
        [DataMember(Name="IsCancellationRequested", EmitDefaultValue=false)]
        public bool? IsCancellationRequested { get; private set; }

        /// <summary>
        /// Gets or Sets CanBeCanceled
        /// </summary>
        [DataMember(Name="CanBeCanceled", EmitDefaultValue=false)]
        public bool? CanBeCanceled { get; private set; }

        /// <summary>
        /// Gets or Sets WaitHandle
        /// </summary>
        [DataMember(Name="WaitHandle", EmitDefaultValue=false)]
        public WaitHandle WaitHandle { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancellationToken {\n");
            sb.Append("  IsCancellationRequested: ").Append(IsCancellationRequested).Append("\n");
            sb.Append("  CanBeCanceled: ").Append(CanBeCanceled).Append("\n");
            sb.Append("  WaitHandle: ").Append(WaitHandle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CancellationToken);
        }

        /// <summary>
        /// Returns true if CancellationToken instances are equal
        /// </summary>
        /// <param name="input">Instance of CancellationToken to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancellationToken input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsCancellationRequested == input.IsCancellationRequested ||
                    (this.IsCancellationRequested != null &&
                    this.IsCancellationRequested.Equals(input.IsCancellationRequested))
                ) && 
                (
                    this.CanBeCanceled == input.CanBeCanceled ||
                    (this.CanBeCanceled != null &&
                    this.CanBeCanceled.Equals(input.CanBeCanceled))
                ) && 
                (
                    this.WaitHandle == input.WaitHandle ||
                    (this.WaitHandle != null &&
                    this.WaitHandle.Equals(input.WaitHandle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsCancellationRequested != null)
                    hashCode = hashCode * 59 + this.IsCancellationRequested.GetHashCode();
                if (this.CanBeCanceled != null)
                    hashCode = hashCode * 59 + this.CanBeCanceled.GetHashCode();
                if (this.WaitHandle != null)
                    hashCode = hashCode * 59 + this.WaitHandle.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
