/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ReceptionInsertNotificationOutcomeResponse
    /// </summary>
    [DataContract]
    public partial class ReceptionInsertNotificationOutcomeResponse :  IEquatable<ReceptionInsertNotificationOutcomeResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceptionInsertNotificationOutcomeResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReceptionInsertNotificationOutcomeResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceptionInsertNotificationOutcomeResponse" /> class.
        /// </summary>
        /// <param name="notificationUIDs">notificationUIDs (required).</param>
        public ReceptionInsertNotificationOutcomeResponse(List<string> notificationUIDs = default(List<string>))
        {
            // to ensure "notificationUIDs" is required (not null)
            if (notificationUIDs == null)
            {
                throw new InvalidDataException("notificationUIDs is a required property for ReceptionInsertNotificationOutcomeResponse and cannot be null");
            }
            else
            {
                this.NotificationUIDs = notificationUIDs;
            }
        }
        
        /// <summary>
        /// Gets or Sets NotificationUIDs
        /// </summary>
        [DataMember(Name="notificationUIDs", EmitDefaultValue=false)]
        public List<string> NotificationUIDs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceptionInsertNotificationOutcomeResponse {\n");
            sb.Append("  NotificationUIDs: ").Append(NotificationUIDs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceptionInsertNotificationOutcomeResponse);
        }

        /// <summary>
        /// Returns true if ReceptionInsertNotificationOutcomeResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceptionInsertNotificationOutcomeResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceptionInsertNotificationOutcomeResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NotificationUIDs == input.NotificationUIDs ||
                    this.NotificationUIDs != null &&
                    this.NotificationUIDs.SequenceEqual(input.NotificationUIDs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NotificationUIDs != null)
                    hashCode = hashCode * 59 + this.NotificationUIDs.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
