/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SafeWaitHandle
    /// </summary>
    [DataContract]
    public partial class SafeWaitHandle :  IEquatable<SafeWaitHandle>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SafeWaitHandle" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public SafeWaitHandle()
        {
        }
        
        /// <summary>
        /// Gets or Sets IsInvalid
        /// </summary>
        [DataMember(Name="IsInvalid", EmitDefaultValue=false)]
        public bool? IsInvalid { get; private set; }

        /// <summary>
        /// Gets or Sets IsClosed
        /// </summary>
        [DataMember(Name="IsClosed", EmitDefaultValue=false)]
        public bool? IsClosed { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SafeWaitHandle {\n");
            sb.Append("  IsInvalid: ").Append(IsInvalid).Append("\n");
            sb.Append("  IsClosed: ").Append(IsClosed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SafeWaitHandle);
        }

        /// <summary>
        /// Returns true if SafeWaitHandle instances are equal
        /// </summary>
        /// <param name="input">Instance of SafeWaitHandle to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SafeWaitHandle input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsInvalid == input.IsInvalid ||
                    (this.IsInvalid != null &&
                    this.IsInvalid.Equals(input.IsInvalid))
                ) && 
                (
                    this.IsClosed == input.IsClosed ||
                    (this.IsClosed != null &&
                    this.IsClosed.Equals(input.IsClosed))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsInvalid != null)
                    hashCode = hashCode * 59 + this.IsInvalid.GetHashCode();
                if (this.IsClosed != null)
                    hashCode = hashCode * 59 + this.IsClosed.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
