/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Represent a failed delivery notification for PA
    /// </summary>
    [DataContract]
    public partial class TransmissionFailedDeliveryPANotification :  IEquatable<TransmissionFailedDeliveryPANotification>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransmissionFailedDeliveryPANotification" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransmissionFailedDeliveryPANotification() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransmissionFailedDeliveryPANotification" /> class.
        /// </summary>
        /// <param name="notDeliveryDateTime">Not delivery date time (required).</param>
        public TransmissionFailedDeliveryPANotification(DateTime? notDeliveryDateTime = default(DateTime?))
        {
            // to ensure "notDeliveryDateTime" is required (not null)
            if (notDeliveryDateTime == null)
            {
                throw new InvalidDataException("notDeliveryDateTime is a required property for TransmissionFailedDeliveryPANotification and cannot be null");
            }
            else
            {
                this.NotDeliveryDateTime = notDeliveryDateTime;
            }
        }
        
        /// <summary>
        /// Not delivery date time
        /// </summary>
        /// <value>Not delivery date time</value>
        [DataMember(Name="notDeliveryDateTime", EmitDefaultValue=false)]
        public DateTime? NotDeliveryDateTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransmissionFailedDeliveryPANotification {\n");
            sb.Append("  NotDeliveryDateTime: ").Append(NotDeliveryDateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransmissionFailedDeliveryPANotification);
        }

        /// <summary>
        /// Returns true if TransmissionFailedDeliveryPANotification instances are equal
        /// </summary>
        /// <param name="input">Instance of TransmissionFailedDeliveryPANotification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransmissionFailedDeliveryPANotification input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NotDeliveryDateTime == input.NotDeliveryDateTime ||
                    (this.NotDeliveryDateTime != null &&
                    this.NotDeliveryDateTime.Equals(input.NotDeliveryDateTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NotDeliveryDateTime != null)
                    hashCode = hashCode * 59 + this.NotDeliveryDateTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
