/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Represent a proof of transmission notification for PA
    /// </summary>
    [DataContract]
    public partial class TransmissionProofOfTransmissionPANotification :  IEquatable<TransmissionProofOfTransmissionPANotification>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransmissionProofOfTransmissionPANotification" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransmissionProofOfTransmissionPANotification() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransmissionProofOfTransmissionPANotification" /> class.
        /// </summary>
        /// <param name="proofOfTransmissionDateTime">Proof of transmission date time (required).</param>
        public TransmissionProofOfTransmissionPANotification(DateTime? proofOfTransmissionDateTime = default(DateTime?))
        {
            // to ensure "proofOfTransmissionDateTime" is required (not null)
            if (proofOfTransmissionDateTime == null)
            {
                throw new InvalidDataException("proofOfTransmissionDateTime is a required property for TransmissionProofOfTransmissionPANotification and cannot be null");
            }
            else
            {
                this.ProofOfTransmissionDateTime = proofOfTransmissionDateTime;
            }
        }
        
        /// <summary>
        /// Proof of transmission date time
        /// </summary>
        /// <value>Proof of transmission date time</value>
        [DataMember(Name="proofOfTransmissionDateTime", EmitDefaultValue=false)]
        public DateTime? ProofOfTransmissionDateTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransmissionProofOfTransmissionPANotification {\n");
            sb.Append("  ProofOfTransmissionDateTime: ").Append(ProofOfTransmissionDateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransmissionProofOfTransmissionPANotification);
        }

        /// <summary>
        /// Returns true if TransmissionProofOfTransmissionPANotification instances are equal
        /// </summary>
        /// <param name="input">Instance of TransmissionProofOfTransmissionPANotification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransmissionProofOfTransmissionPANotification input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProofOfTransmissionDateTime == input.ProofOfTransmissionDateTime ||
                    (this.ProofOfTransmissionDateTime != null &&
                    this.ProofOfTransmissionDateTime.Equals(input.ProofOfTransmissionDateTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProofOfTransmissionDateTime != null)
                    hashCode = hashCode * 59 + this.ProofOfTransmissionDateTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
