/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PA Notifications
    /// </summary>
    [DataContract]
    public partial class TransmissionPANotification :  IEquatable<TransmissionPANotification>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransmissionPANotification" /> class.
        /// </summary>
        /// <param name="deliveryReceipt">Delivery receipt notification.</param>
        /// <param name="rejection">Rejection notification.</param>
        /// <param name="failedDelivery">Failed delivery notification.</param>
        /// <param name="outcome">Outcome notification.</param>
        /// <param name="proofOfTransmission">Proof of transmission notification.</param>
        public TransmissionPANotification(TransmissionDeliveryReceiptPANotification deliveryReceipt = default(TransmissionDeliveryReceiptPANotification), TransmissionRejectionPANotification rejection = default(TransmissionRejectionPANotification), TransmissionFailedDeliveryPANotification failedDelivery = default(TransmissionFailedDeliveryPANotification), TransmissionOutcomePANotification outcome = default(TransmissionOutcomePANotification), TransmissionProofOfTransmissionPANotification proofOfTransmission = default(TransmissionProofOfTransmissionPANotification))
        {
            this.DeliveryReceipt = deliveryReceipt;
            this.Rejection = rejection;
            this.FailedDelivery = failedDelivery;
            this.Outcome = outcome;
            this.ProofOfTransmission = proofOfTransmission;
        }
        
        /// <summary>
        /// Delivery receipt notification
        /// </summary>
        /// <value>Delivery receipt notification</value>
        [DataMember(Name="deliveryReceipt", EmitDefaultValue=false)]
        public TransmissionDeliveryReceiptPANotification DeliveryReceipt { get; set; }

        /// <summary>
        /// Rejection notification
        /// </summary>
        /// <value>Rejection notification</value>
        [DataMember(Name="rejection", EmitDefaultValue=false)]
        public TransmissionRejectionPANotification Rejection { get; set; }

        /// <summary>
        /// Failed delivery notification
        /// </summary>
        /// <value>Failed delivery notification</value>
        [DataMember(Name="failedDelivery", EmitDefaultValue=false)]
        public TransmissionFailedDeliveryPANotification FailedDelivery { get; set; }

        /// <summary>
        /// Outcome notification
        /// </summary>
        /// <value>Outcome notification</value>
        [DataMember(Name="outcome", EmitDefaultValue=false)]
        public TransmissionOutcomePANotification Outcome { get; set; }

        /// <summary>
        /// Proof of transmission notification
        /// </summary>
        /// <value>Proof of transmission notification</value>
        [DataMember(Name="proofOfTransmission", EmitDefaultValue=false)]
        public TransmissionProofOfTransmissionPANotification ProofOfTransmission { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransmissionPANotification {\n");
            sb.Append("  DeliveryReceipt: ").Append(DeliveryReceipt).Append("\n");
            sb.Append("  Rejection: ").Append(Rejection).Append("\n");
            sb.Append("  FailedDelivery: ").Append(FailedDelivery).Append("\n");
            sb.Append("  Outcome: ").Append(Outcome).Append("\n");
            sb.Append("  ProofOfTransmission: ").Append(ProofOfTransmission).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransmissionPANotification);
        }

        /// <summary>
        /// Returns true if TransmissionPANotification instances are equal
        /// </summary>
        /// <param name="input">Instance of TransmissionPANotification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransmissionPANotification input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DeliveryReceipt == input.DeliveryReceipt ||
                    (this.DeliveryReceipt != null &&
                    this.DeliveryReceipt.Equals(input.DeliveryReceipt))
                ) && 
                (
                    this.Rejection == input.Rejection ||
                    (this.Rejection != null &&
                    this.Rejection.Equals(input.Rejection))
                ) && 
                (
                    this.FailedDelivery == input.FailedDelivery ||
                    (this.FailedDelivery != null &&
                    this.FailedDelivery.Equals(input.FailedDelivery))
                ) && 
                (
                    this.Outcome == input.Outcome ||
                    (this.Outcome != null &&
                    this.Outcome.Equals(input.Outcome))
                ) && 
                (
                    this.ProofOfTransmission == input.ProofOfTransmission ||
                    (this.ProofOfTransmission != null &&
                    this.ProofOfTransmission.Equals(input.ProofOfTransmission))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DeliveryReceipt != null)
                    hashCode = hashCode * 59 + this.DeliveryReceipt.GetHashCode();
                if (this.Rejection != null)
                    hashCode = hashCode * 59 + this.Rejection.GetHashCode();
                if (this.FailedDelivery != null)
                    hashCode = hashCode * 59 + this.FailedDelivery.GetHashCode();
                if (this.Outcome != null)
                    hashCode = hashCode * 59 + this.Outcome.GetHashCode();
                if (this.ProofOfTransmission != null)
                    hashCode = hashCode * 59 + this.ProofOfTransmission.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
