/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Represent the Subscription response.
    /// </summary>
    [DataContract]
    public partial class TransmissionSubscribeResponse :  IEquatable<TransmissionSubscribeResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransmissionSubscribeResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransmissionSubscribeResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransmissionSubscribeResponse" /> class.
        /// </summary>
        /// <param name="subscriptionUID">The unique identifier related to the new Subscription. (required).</param>
        /// <param name="warningMessage">A message where find informations about raised warnings during the subscription. (required).</param>
        public TransmissionSubscribeResponse(string subscriptionUID = default(string), string warningMessage = default(string))
        {
            // to ensure "subscriptionUID" is required (not null)
            if (subscriptionUID == null)
            {
                throw new InvalidDataException("subscriptionUID is a required property for TransmissionSubscribeResponse and cannot be null");
            }
            else
            {
                this.SubscriptionUID = subscriptionUID;
            }
            // to ensure "warningMessage" is required (not null)
            if (warningMessage == null)
            {
                throw new InvalidDataException("warningMessage is a required property for TransmissionSubscribeResponse and cannot be null");
            }
            else
            {
                this.WarningMessage = warningMessage;
            }
        }
        
        /// <summary>
        /// The unique identifier related to the new Subscription.
        /// </summary>
        /// <value>The unique identifier related to the new Subscription.</value>
        [DataMember(Name="subscriptionUID", EmitDefaultValue=false)]
        public string SubscriptionUID { get; set; }

        /// <summary>
        /// A message where find informations about raised warnings during the subscription.
        /// </summary>
        /// <value>A message where find informations about raised warnings during the subscription.</value>
        [DataMember(Name="warningMessage", EmitDefaultValue=false)]
        public string WarningMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransmissionSubscribeResponse {\n");
            sb.Append("  SubscriptionUID: ").Append(SubscriptionUID).Append("\n");
            sb.Append("  WarningMessage: ").Append(WarningMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransmissionSubscribeResponse);
        }

        /// <summary>
        /// Returns true if TransmissionSubscribeResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TransmissionSubscribeResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransmissionSubscribeResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SubscriptionUID == input.SubscriptionUID ||
                    (this.SubscriptionUID != null &&
                    this.SubscriptionUID.Equals(input.SubscriptionUID))
                ) && 
                (
                    this.WarningMessage == input.WarningMessage ||
                    (this.WarningMessage != null &&
                    this.WarningMessage.Equals(input.WarningMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SubscriptionUID != null)
                    hashCode = hashCode * 59 + this.SubscriptionUID.GetHashCode();
                if (this.WarningMessage != null)
                    hashCode = hashCode * 59 + this.WarningMessage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
