/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WaitHandle
    /// </summary>
    [DataContract]
    public partial class WaitHandle :  IEquatable<WaitHandle>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WaitHandle" /> class.
        /// </summary>
        /// <param name="handle">handle.</param>
        /// <param name="safeWaitHandle">safeWaitHandle.</param>
        public WaitHandle(Object handle = default(Object), SafeWaitHandle safeWaitHandle = default(SafeWaitHandle))
        {
            this.Handle = handle;
            this.SafeWaitHandle = safeWaitHandle;
        }
        
        /// <summary>
        /// Gets or Sets Handle
        /// </summary>
        [DataMember(Name="Handle", EmitDefaultValue=false)]
        public Object Handle { get; set; }

        /// <summary>
        /// Gets or Sets SafeWaitHandle
        /// </summary>
        [DataMember(Name="SafeWaitHandle", EmitDefaultValue=false)]
        public SafeWaitHandle SafeWaitHandle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WaitHandle {\n");
            sb.Append("  Handle: ").Append(Handle).Append("\n");
            sb.Append("  SafeWaitHandle: ").Append(SafeWaitHandle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WaitHandle);
        }

        /// <summary>
        /// Returns true if WaitHandle instances are equal
        /// </summary>
        /// <param name="input">Instance of WaitHandle to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WaitHandle input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Handle == input.Handle ||
                    (this.Handle != null &&
                    this.Handle.Equals(input.Handle))
                ) && 
                (
                    this.SafeWaitHandle == input.SafeWaitHandle ||
                    (this.SafeWaitHandle != null &&
                    this.SafeWaitHandle.Equals(input.SafeWaitHandle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Handle != null)
                    hashCode = hashCode * 59 + this.Handle.GetHashCode();
                if (this.SafeWaitHandle != null)
                    hashCode = hashCode * 59 + this.SafeWaitHandle.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
