/* 
 * REGISTRY API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAoosApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Lists the Uos available for the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>AooUosListResponse</returns>
        AooUosListResponse AooUos (Guid? aooUID, string xAuthorization, string serviceUID = null);

        /// <summary>
        /// Lists the Uos available for the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>ApiResponse of AooUosListResponse</returns>
        ApiResponse<AooUosListResponse> AooUosWithHttpInfo (Guid? aooUID, string xAuthorization, string serviceUID = null);
        /// <summary>
        /// Lists the Aoos available for the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>AoosListResponse</returns>
        AoosListResponse Aoos (string xAuthorization, string serviceUID = null);

        /// <summary>
        /// Lists the Aoos available for the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>ApiResponse of AoosListResponse</returns>
        ApiResponse<AoosListResponse> AoosWithHttpInfo (string xAuthorization, string serviceUID = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Lists the Uos available for the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>Task of AooUosListResponse</returns>
        System.Threading.Tasks.Task<AooUosListResponse> AooUosAsync (Guid? aooUID, string xAuthorization, string serviceUID = null);

        /// <summary>
        /// Lists the Uos available for the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>Task of ApiResponse (AooUosListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AooUosListResponse>> AooUosAsyncWithHttpInfo (Guid? aooUID, string xAuthorization, string serviceUID = null);
        /// <summary>
        /// Lists the Aoos available for the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>Task of AoosListResponse</returns>
        System.Threading.Tasks.Task<AoosListResponse> AoosAsync (string xAuthorization, string serviceUID = null);

        /// <summary>
        /// Lists the Aoos available for the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>Task of ApiResponse (AoosListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AoosListResponse>> AoosAsyncWithHttpInfo (string xAuthorization, string serviceUID = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AoosApi : IAoosApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AoosApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AoosApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AoosApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AoosApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Lists the Uos available for the user 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>AooUosListResponse</returns>
        public AooUosListResponse AooUos (Guid? aooUID, string xAuthorization, string serviceUID = null)
        {
             ApiResponse<AooUosListResponse> localVarResponse = AooUosWithHttpInfo(aooUID, xAuthorization, serviceUID);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Lists the Uos available for the user 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>ApiResponse of AooUosListResponse</returns>
        public ApiResponse< AooUosListResponse > AooUosWithHttpInfo (Guid? aooUID, string xAuthorization, string serviceUID = null)
        {
            // verify the required parameter 'aooUID' is set
            if (aooUID == null)
                throw new ApiException(400, "Missing required parameter 'aooUID' when calling AoosApi->AooUos");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling AoosApi->AooUos");

            var localVarPath = "/api/v1/aoos/{aooUID}/uos";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aooUID != null) localVarPathParams.Add("aooUID", this.Configuration.ApiClient.ParameterToString(aooUID)); // path parameter
            if (serviceUID != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "serviceUID", serviceUID)); // query parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AooUos", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AooUosListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AooUosListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AooUosListResponse)));
        }

        /// <summary>
        /// Lists the Uos available for the user 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>Task of AooUosListResponse</returns>
        public async System.Threading.Tasks.Task<AooUosListResponse> AooUosAsync (Guid? aooUID, string xAuthorization, string serviceUID = null)
        {
             ApiResponse<AooUosListResponse> localVarResponse = await AooUosAsyncWithHttpInfo(aooUID, xAuthorization, serviceUID);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Lists the Uos available for the user 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>Task of ApiResponse (AooUosListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AooUosListResponse>> AooUosAsyncWithHttpInfo (Guid? aooUID, string xAuthorization, string serviceUID = null)
        {
            // verify the required parameter 'aooUID' is set
            if (aooUID == null)
                throw new ApiException(400, "Missing required parameter 'aooUID' when calling AoosApi->AooUos");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling AoosApi->AooUos");

            var localVarPath = "/api/v1/aoos/{aooUID}/uos";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aooUID != null) localVarPathParams.Add("aooUID", this.Configuration.ApiClient.ParameterToString(aooUID)); // path parameter
            if (serviceUID != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "serviceUID", serviceUID)); // query parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AooUos", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AooUosListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AooUosListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AooUosListResponse)));
        }

        /// <summary>
        /// Lists the Aoos available for the user 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>AoosListResponse</returns>
        public AoosListResponse Aoos (string xAuthorization, string serviceUID = null)
        {
             ApiResponse<AoosListResponse> localVarResponse = AoosWithHttpInfo(xAuthorization, serviceUID);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Lists the Aoos available for the user 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>ApiResponse of AoosListResponse</returns>
        public ApiResponse< AoosListResponse > AoosWithHttpInfo (string xAuthorization, string serviceUID = null)
        {
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling AoosApi->Aoos");

            var localVarPath = "/api/v1/aoos";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (serviceUID != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "serviceUID", serviceUID)); // query parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Aoos", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AoosListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AoosListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AoosListResponse)));
        }

        /// <summary>
        /// Lists the Aoos available for the user 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>Task of AoosListResponse</returns>
        public async System.Threading.Tasks.Task<AoosListResponse> AoosAsync (string xAuthorization, string serviceUID = null)
        {
             ApiResponse<AoosListResponse> localVarResponse = await AoosAsyncWithHttpInfo(xAuthorization, serviceUID);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Lists the Aoos available for the user 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <param name="serviceUID">Filter aoos for a serviceUID (optional)</param>
        /// <returns>Task of ApiResponse (AoosListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AoosListResponse>> AoosAsyncWithHttpInfo (string xAuthorization, string serviceUID = null)
        {
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling AoosApi->Aoos");

            var localVarPath = "/api/v1/aoos";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (serviceUID != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "serviceUID", serviceUID)); // query parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Aoos", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AoosListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AoosListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AoosListResponse)));
        }

    }
}
