/* 
 * IX.FE API V3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReceptionInvoicesManagementApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Insert an outcome notification
        /// </summary>
        /// <remarks>
        /// The description is mandatory only for reject
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="uoUID">UO unique identifier</param>
        /// <param name="invoiceUID">Invoice unique identifier</param>
        /// <param name="request">Outcome request</param>
        /// <param name="accept">Accept or reject the invoice</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ReceptionInsertNotificationOutcomeResponse</returns>
        ReceptionInsertNotificationOutcomeResponse ReceptionInsertNotificationOutcome (Guid? aooUID, string uoUID, string invoiceUID, ReceptionInsertNotificationOutcomeRequest request, bool? accept, string xAuthorization);

        /// <summary>
        /// Insert an outcome notification
        /// </summary>
        /// <remarks>
        /// The description is mandatory only for reject
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="uoUID">UO unique identifier</param>
        /// <param name="invoiceUID">Invoice unique identifier</param>
        /// <param name="request">Outcome request</param>
        /// <param name="accept">Accept or reject the invoice</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of ReceptionInsertNotificationOutcomeResponse</returns>
        ApiResponse<ReceptionInsertNotificationOutcomeResponse> ReceptionInsertNotificationOutcomeWithHttpInfo (Guid? aooUID, string uoUID, string invoiceUID, ReceptionInsertNotificationOutcomeRequest request, bool? accept, string xAuthorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Insert an outcome notification
        /// </summary>
        /// <remarks>
        /// The description is mandatory only for reject
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="uoUID">UO unique identifier</param>
        /// <param name="invoiceUID">Invoice unique identifier</param>
        /// <param name="request">Outcome request</param>
        /// <param name="accept">Accept or reject the invoice</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ReceptionInsertNotificationOutcomeResponse</returns>
        System.Threading.Tasks.Task<ReceptionInsertNotificationOutcomeResponse> ReceptionInsertNotificationOutcomeAsync (Guid? aooUID, string uoUID, string invoiceUID, ReceptionInsertNotificationOutcomeRequest request, bool? accept, string xAuthorization);

        /// <summary>
        /// Insert an outcome notification
        /// </summary>
        /// <remarks>
        /// The description is mandatory only for reject
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="uoUID">UO unique identifier</param>
        /// <param name="invoiceUID">Invoice unique identifier</param>
        /// <param name="request">Outcome request</param>
        /// <param name="accept">Accept or reject the invoice</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (ReceptionInsertNotificationOutcomeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReceptionInsertNotificationOutcomeResponse>> ReceptionInsertNotificationOutcomeAsyncWithHttpInfo (Guid? aooUID, string uoUID, string invoiceUID, ReceptionInsertNotificationOutcomeRequest request, bool? accept, string xAuthorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ReceptionInvoicesManagementApi : IReceptionInvoicesManagementApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReceptionInvoicesManagementApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReceptionInvoicesManagementApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReceptionInvoicesManagementApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ReceptionInvoicesManagementApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Insert an outcome notification The description is mandatory only for reject
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="uoUID">UO unique identifier</param>
        /// <param name="invoiceUID">Invoice unique identifier</param>
        /// <param name="request">Outcome request</param>
        /// <param name="accept">Accept or reject the invoice</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ReceptionInsertNotificationOutcomeResponse</returns>
        public ReceptionInsertNotificationOutcomeResponse ReceptionInsertNotificationOutcome (Guid? aooUID, string uoUID, string invoiceUID, ReceptionInsertNotificationOutcomeRequest request, bool? accept, string xAuthorization)
        {
             ApiResponse<ReceptionInsertNotificationOutcomeResponse> localVarResponse = ReceptionInsertNotificationOutcomeWithHttpInfo(aooUID, uoUID, invoiceUID, request, accept, xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Insert an outcome notification The description is mandatory only for reject
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="uoUID">UO unique identifier</param>
        /// <param name="invoiceUID">Invoice unique identifier</param>
        /// <param name="request">Outcome request</param>
        /// <param name="accept">Accept or reject the invoice</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of ReceptionInsertNotificationOutcomeResponse</returns>
        public ApiResponse< ReceptionInsertNotificationOutcomeResponse > ReceptionInsertNotificationOutcomeWithHttpInfo (Guid? aooUID, string uoUID, string invoiceUID, ReceptionInsertNotificationOutcomeRequest request, bool? accept, string xAuthorization)
        {
            // verify the required parameter 'aooUID' is set
            if (aooUID == null)
                throw new ApiException(400, "Missing required parameter 'aooUID' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'uoUID' is set
            if (uoUID == null)
                throw new ApiException(400, "Missing required parameter 'uoUID' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'invoiceUID' is set
            if (invoiceUID == null)
                throw new ApiException(400, "Missing required parameter 'invoiceUID' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");

            var localVarPath = "/api/v3.1/reception/management/aoos/{aooUID}/uos/{uoUID}/invoices/{invoiceUID}/notifications";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aooUID != null) localVarPathParams.Add("aooUID", this.Configuration.ApiClient.ParameterToString(aooUID)); // path parameter
            if (uoUID != null) localVarPathParams.Add("uoUID", this.Configuration.ApiClient.ParameterToString(uoUID)); // path parameter
            if (invoiceUID != null) localVarPathParams.Add("invoiceUID", this.Configuration.ApiClient.ParameterToString(invoiceUID)); // path parameter
            if (accept != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "accept", accept)); // query parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ReceptionInsertNotificationOutcome", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReceptionInsertNotificationOutcomeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReceptionInsertNotificationOutcomeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReceptionInsertNotificationOutcomeResponse)));
        }

        /// <summary>
        /// Insert an outcome notification The description is mandatory only for reject
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="uoUID">UO unique identifier</param>
        /// <param name="invoiceUID">Invoice unique identifier</param>
        /// <param name="request">Outcome request</param>
        /// <param name="accept">Accept or reject the invoice</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ReceptionInsertNotificationOutcomeResponse</returns>
        public async System.Threading.Tasks.Task<ReceptionInsertNotificationOutcomeResponse> ReceptionInsertNotificationOutcomeAsync (Guid? aooUID, string uoUID, string invoiceUID, ReceptionInsertNotificationOutcomeRequest request, bool? accept, string xAuthorization)
        {
             ApiResponse<ReceptionInsertNotificationOutcomeResponse> localVarResponse = await ReceptionInsertNotificationOutcomeAsyncWithHttpInfo(aooUID, uoUID, invoiceUID, request, accept, xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Insert an outcome notification The description is mandatory only for reject
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="uoUID">UO unique identifier</param>
        /// <param name="invoiceUID">Invoice unique identifier</param>
        /// <param name="request">Outcome request</param>
        /// <param name="accept">Accept or reject the invoice</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (ReceptionInsertNotificationOutcomeResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ReceptionInsertNotificationOutcomeResponse>> ReceptionInsertNotificationOutcomeAsyncWithHttpInfo (Guid? aooUID, string uoUID, string invoiceUID, ReceptionInsertNotificationOutcomeRequest request, bool? accept, string xAuthorization)
        {
            // verify the required parameter 'aooUID' is set
            if (aooUID == null)
                throw new ApiException(400, "Missing required parameter 'aooUID' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'uoUID' is set
            if (uoUID == null)
                throw new ApiException(400, "Missing required parameter 'uoUID' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'invoiceUID' is set
            if (invoiceUID == null)
                throw new ApiException(400, "Missing required parameter 'invoiceUID' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling ReceptionInvoicesManagementApi->ReceptionInsertNotificationOutcome");

            var localVarPath = "/api/v3.1/reception/management/aoos/{aooUID}/uos/{uoUID}/invoices/{invoiceUID}/notifications";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aooUID != null) localVarPathParams.Add("aooUID", this.Configuration.ApiClient.ParameterToString(aooUID)); // path parameter
            if (uoUID != null) localVarPathParams.Add("uoUID", this.Configuration.ApiClient.ParameterToString(uoUID)); // path parameter
            if (invoiceUID != null) localVarPathParams.Add("invoiceUID", this.Configuration.ApiClient.ParameterToString(invoiceUID)); // path parameter
            if (accept != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "accept", accept)); // query parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ReceptionInsertNotificationOutcome", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReceptionInsertNotificationOutcomeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReceptionInsertNotificationOutcomeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReceptionInsertNotificationOutcomeResponse)));
        }

    }
}
